### ISSUE TITLE
Lack of entry_pt pthread_create return value causes segfault in parsec.canneal

### ISSUE THREAD

**Issue by jic23** [cirosantilli/parsec-benchmark#5]
https://github.com/cirosantilli/parsec-benchmark/blob/1d4a1025e06a4f7ad23f1ca7f908e0135e712585/pkgs/kernels/canneal/src/main.cpp#L137

The dumb approach of returning NULL from this function seems to solve the segfault. I haven't done any sanity checking on whether this is the 'right' fix or not.

**Comment by cirosantilli** [comment]
OMG how can a benchmark be so broken.

**Comment by jic23** [comment]
It did rather surprise me.  Thanks for your hard work on sorting these out btw.  I was doing pretty much the same thing and got most of the way through making the same changes you did and then came across your repo!  Guess I should have done some more googling.

**Comment by cirosantilli** [comment]
> Guess I should have done some more googling.

The story of my life! If you find any other fixes, let me know.
